AWSTemplateFormatVersion: 2010-09-09
Parameters:
  ChaimUser:
    Type: String
    Description: The IAM Chaim User
  ChaimUserPoolName:
    Type: String
    Description: Cognito User Pool Name
  ChaimCIDROctet0:
    Type: String
    Description: First octet of CIDR Block
  ChaimCIDROctet1:
    Type: String
    Description: Second octet of CIDR Block
  ChaimDbMasterUsername:
    Type: String
    Description: Chaim RDS DB Master Username
  Owner:
    Type: String
    Description: The owner of the product
  Product:
    Type: String
    Description: The product this stack provides
  Environment:
    Type: String
    Description: The environment the product will be built in
Resources:
  ChaimCognito0:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.eu-west-1.amazonaws.com/chaimcloudformationtemplates/fe7eebe66668f9631002148ddcc4489c.template
      Parameters:
        ChaimUserPoolName:
          Ref: ChaimUserPoolName
        Owner:
          Ref: Owner
        Product:
          Ref: Product
        Environment:
          Ref: Environment
  ChaimIAM0:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.eu-west-1.amazonaws.com/chaimcloudformationtemplates/06c1c38a0fc0ce9a8043cc198cfb5433.template
      Parameters:
        ChaimCognitoUserPool:
          Fn::GetAtt:
          - ChaimCognito0
          - Outputs.ChaimCognitoUserPoolId
        ChaimUser:
          Ref: ChaimUser
        Environment:
          Ref: Environment
        Owner:
          Ref: Owner
        Product:
          Ref: Product
    DependsOn: ChaimCognito0
  ChaimKMS0:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.eu-west-1.amazonaws.com/chaimcloudformationtemplates/b646364b19393a4ea2854d690eebf8d1.template
      Parameters:
        Environment:
          Ref: Environment
        Owner:
          Ref: Owner
        Product:
          Ref: Product
    DependsOn: ChaimIAM0
  ChaimIAM1:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.eu-west-1.amazonaws.com/chaimcloudformationtemplates/b8f85de70ee9cb38e91a9d4d477f9bf5.template
      Parameters:
        ChaimKMSKey:
          Fn::GetAtt:
          - ChaimKMS0
          - Outputs.ChaimKMSKeyId
        Environment:
          Ref: Environment
        Owner:
          Ref: Owner
        Product:
          Ref: Product
    DependsOn: ChaimKMS0
  ChaimSNS0:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.eu-west-1.amazonaws.com/chaimcloudformationtemplates/b4daaaaf2f7249b8c4ba542fec5ad758.template
      Parameters:
        Environment:
          Ref: Environment
        Owner:
          Ref: Owner
        Product:
          Ref: Product
    DependsOn: ChaimIAM1
  ChaimEC20:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.eu-west-1.amazonaws.com/chaimcloudformationtemplates/6579e34c9c5e37a07c788b67fff3a7ab.template
      Parameters:
        ChaimCIDROctet0:
          Ref: ChaimCIDROctet0
        ChaimCIDROctet1:
          Ref: ChaimCIDROctet1
        Environment:
          Ref: Environment
        Owner:
          Ref: Owner
        Product:
          Ref: Product
    DependsOn: ChaimSNS0
  ChaimRDS0:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.eu-west-1.amazonaws.com/chaimcloudformationtemplates/e2e15549adbb5f175f64635fe2bab7db.template
      Parameters:
        ChaimKMSKey:
          Fn::GetAtt:
          - ChaimKMS0
          - Outputs.ChaimKMSKeyId
        ChaimDbSG:
          Fn::GetAtt:
          - ChaimEC20
          - Outputs.ChaimDbSGId
        ChaimSubnet1:
          Fn::GetAtt:
          - ChaimEC20
          - Outputs.ChaimSubnet1Id
        ChaimSubnet2:
          Fn::GetAtt:
          - ChaimEC20
          - Outputs.ChaimSubnet2Id
        ChaimDbMasterUsername:
          Ref: ChaimDbMasterUsername
        Environment:
          Ref: Environment
        Owner:
          Ref: Owner
        Product:
          Ref: Product
    DependsOn: ChaimEC20
