---
  AWSTemplateFormatVersion: 2010-09-09
  Parameters: 
    ChaimUser:
      Type: String
      Description: The IAM Chaim User
    ChaimUserPoolName:
      Type: String
      Description: Cognito User Pool Name
    ChaimCIDROctet0:
      Type: String
      Description: First octet of CIDR Block
    ChaimCIDROctet1:
      Type: String
      Description: Second octet of CIDR Block
    Owner:
      Type: String
      Description: The owner of the product
    Product:
      Type: String
      Description: The product this stack provides
    Environment:
      Type: String
      Description: The environment the product will be built in
  Resources:
    ChaimCognito0:
      Type: AWS::CloudFormation::Stack
      Properties:
        TemplateURL: chaim_cognito0.yaml
        Parameters:
          ChaimUserPoolName: !Ref ChaimUserPoolName
          Owner: !Ref Owner
          Product: !Ref Product
          Environment: !Ref Environment        
    ChaimIAM0:
      Type: AWS::CloudFormation::Stack
      Properties:
        TemplateURL: chaim_iam0.yaml
        Parameters:
          ChaimCognitoUserPool: !GetAtt ChaimCognito0.Outputs.ChaimCognitoUserPoolId
          ChaimUser: !Ref ChaimUser
          Environment: !Ref Environment
          Owner: !Ref Owner
          Product: !Ref Product
      DependsOn: ChaimCognito0
    ChaimKMS0:
      Type: AWS::CloudFormation::Stack
      Properties:
        TemplateURL: chaim_kms0.yaml
        Parameters:
          Environment: !Ref Environment
          Owner: !Ref Owner
          Product: !Ref Product
      DependsOn: ChaimIAM0
    ChaimIAM1:
      Type: AWS::CloudFormation::Stack
      Properties:
        TemplateURL: chaim_iam1.yaml
        Parameters:
          ChaimKMSKey: !GetAtt ChaimKMS0.Outputs.ChaimKMSKeyId
          Environment: !Ref Environment
          Owner: !Ref Owner
          Product: !Ref Product
      DependsOn: ChaimKMS0
    ChaimSNS0:
      Type: AWS::CloudFormation::Stack
      Properties:
        TemplateURL: chaim_sns0.yaml
        Parameters:
          Environment: !Ref Environment
          Owner: !Ref Owner
          Product: !Ref Product
      DependsOn: ChaimIAM1
    ChaimEC20:
      Type: AWS::CloudFormation::Stack
      Properties:
        TemplateURL: chaim_ec20.yaml
        Parameters:
          ChaimCIDROctet0: !Ref ChaimCIDROctet0
          ChaimCIDROctet1: !Ref ChaimCIDROctet1
          Environment: !Ref Environment
          Owner: !Ref Owner
          Product: !Ref Product
      DependsOn:
        ChaimSNS0
