AWSTemplateFormatVersion: 2010-09-09
Parameters:
  ChaimUser:
    Type: String
    Description: The IAM Chaim User
  ChaimUserRole:
    Type: String
    Description: Tag for Chaim User
  ChaimLambdaRDSRoleName:
    Type: String
    Description: Tag for Chaim Lambda RDS Role
  ChaimLambdaKeymanRoleName:
    Type: String
    Description: Tag for Chaim Lambda Keyman Role
  ChaimUserPoolName:
    Type: String
    Description: Cognito User Pool Name
  Owner:
    Type: String
    Description: The owner of the product
  Product:
    Type: String
    Description: The product this stack provides
  Environment:
    Type: String
    Description: The environment the product will be built in
Resources:
  ChaimCognito0:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.eu-west-1.amazonaws.com/chaimcloudformationtemplates/fe7eebe66668f9631002148ddcc4489c.template
      Parameters:
        ChaimUserPoolName:
          Ref: ChaimUserPoolName
        Owner:
          Ref: Owner
        Product:
          Ref: Product
        Environment:
          Ref: Environment
  ChaimIAM0:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.eu-west-1.amazonaws.com/chaimcloudformationtemplates/dedb76edde970203063bcdeb5a5f8759.template
      Parameters:
        ChaimCognitoUserPool:
          Fn::GetAtt:
          - ChaimCognito0
          - Outputs.ChaimCognitoUserPoolId
        ChaimLambdaRDSRoleName:
          Ref: ChaimLambdaRDSRoleName
        ChaimLambdaKeymanRoleName:
          Ref: ChaimLambdaKeymanRoleName
        ChaimUser:
          Ref: ChaimUser
        ChaimUserRole:
          Ref: ChaimUserRole
        Environment:
          Ref: Environment
        Owner:
          Ref: Owner
        Product:
          Ref: Product
    DependsOn: ChaimCognito0
  ChaimKMS0:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.eu-west-1.amazonaws.com/chaimcloudformationtemplates/c6205d7b9b4767b0e216c65f9cd1fc81.template
      Parameters:
        ChaimLambdaRDSRoleName:
          Ref: ChaimLambdaRDSRoleName
        Environment:
          Ref: Environment
        Owner:
          Ref: Owner
        Product:
          Ref: Product
    DependsOn: ChaimIAM0
  ChaimIAM1:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.eu-west-1.amazonaws.com/chaimcloudformationtemplates/87b947caaf1d3b4981b817a584330870.template
      Parameters:
        ChaimKMSKey:
          Fn::GetAtt:
          - ChaimKMS0
          - Outputs.ChaimKMSKeyId
        ChaimLambdaRDSRoleName:
          Ref: ChaimLambdaRDSRoleName
        ChaimLambdaKeymanRoleName:
          Ref: ChaimLambdaKeymanRoleName
        Environment:
          Ref: Environment
        Owner:
          Ref: Owner
        Product:
          Ref: Product
    DependsOn: ChaimKMS0
