---
  AWSTemplateFormatVersion: 2010-09-09
  Parameters:
    ChaimKMSKey:
      Type: String
      Description: Chaim KMS Key
    ChaimDbSG:
      Type: String
      Description: Chaim DB Security Group
    ChaimSubnet1:
      Type: String
      Description: Chaim private subnet 1
    ChaimSubnet2:
      Type: String
      Description: Chaim private subnet 2
    ChaimDbMasterUsername:
      Type: String
      Description: Chaim RDS DB Master Username
    Owner:
      Type: String
      Description: The owner of the product
    Product:
      Type: String
      Description: The product this stack provides
    Environment:
      Type: String
      Description: The environment the product will be built in
  Resources:
    ChaimSecretsManagerDbPw:
      Type: AWS::SecretsManager::Secret
      Properties: 
        Description: "Chaim RDS DB Master Password"
        KmsKeyId: !Ref ChaimKMSKey
        Name: ChaimSecretsManagerDbPw
        GenerateSecretString:
          SecretStringTemplate:
            !Join
              - ''
              - - '{"username": "'
                - !Ref ChaimDbMasterUsername
                - '" }'
          GenerateStringKey: 'password'
          ExcludeCharacters: "`/\"@'\\"
        Tags:
          - Key: Name
            Value: ChaimDbMasterPw
          - Key: Owner
            Value: !Ref Owner
          - Key: Product
            Value: !Ref Product
          - Key: Environment
            Value: !Ref Environment
    ChaimRDSDbSubnetGroup:
      Type: AWS::RDS::DBSubnetGroup
      Properties:
        DBSubnetGroupDescription: "Chaim RDS DB Subnet Group"
        DBSubnetGroupName: ChaimRDSDbSubnetGroup
        SubnetIds:
          - !Ref ChaimSubnet1
          - !Ref ChaimSubnet2
        Tags:
          - Key: Name
            Value: ChaimRDSDbSubnetGroup
          - Key: Owner
            Value: !Ref Owner
          - Key: Product
            Value: !Ref Product
          - Key: Environment
            Value: !Ref Environment
      DependsOn: ChaimSecretsManagerDbPw
    ChaimRDSDb:
      Type: AWS::RDS::DBInstance
      Properties:
        AllocatedStorage: 20
        BackupRetentionPeriod: 7
        DBInstanceIdentifier: ChaimRDSDb
        DBName: chaimdb
        DBInstanceClass: db.t3.micro
        DBSubnetGroupName: !Ref ChaimRDSDbSubnetGroup
        DeletionProtection: True
        Engine: MariaDB
        EngineVersion: 10.3.13
        KmsKeyId: !Ref ChaimKMSKey
        MasterUsername: 
          !Sub
            - "{{resolve:secretsmanager:${Username}:SecretString:username}}"
            - { Username: !Ref ChaimSecretsManagerDbPw }
        MasterUserPassword:
          !Sub
            - "{{resolve:secretsmanager:${Password}:SecretString:password}}"
            - { Password: !Ref ChaimSecretsManagerDbPw }
        MultiAZ: True
        StorageEncrypted: True
        StorageType: gp2
        VPCSecurityGroups: 
          - !Ref ChaimDbSG
        Tags:
          - Key: Name
            Value: ChaimRDSDb
          - Key: Owner
            Value: !Ref Owner
          - Key: Product
            Value: !Ref Product
          - Key: Environment
            Value: !Ref Environment
          - Key: Role
            Value: ChaimRDSDb
      DependsOn: ChaimRDSDbSubnetGroup
    ChaimSecretRDSInstanceAttachment:
      Type: AWS::SecretsManager::SecretTargetAttachment
      Properties:
        SecretId: !Ref ChaimSecretsManagerDbPw
        TargetId: !Ref ChaimRDSDb
        TargetType: AWS::RDS::DBInstance
      DependsOn: ChaimRDSDb
  Outputs:
    ChaimSecretsManagerDbPwId:
      Value: !Ref ChaimSecretsManagerDbPw
    ChaimRDSDbSubnetGroupId:
      Value: !Ref ChaimRDSDbSubnetGroup
    ChaimRDSDbId:
      Value: !Ref ChaimRDSDb
    ChaimRDSDbEndpointId:
      Value: !GetAtt ChaimRDSDb.Endpoint.Address
    ChaimRDSDbPortId:
      Value: !GetAtt ChaimRDSDb.Endpoint.Port
