AWSTemplateFormatVersion: 2010-09-09
Parameters:
  ChaimUser:
    Type: String
    Description: The IAM Chaim User
  ChaimUserRole:
    Type: String
    Description: Tag for Chaim User
  ChaimRole:
    Type: String
    Description: Tag for Chaim Role
  ChaimKMSKey:
    Type: String
    Description: The KMS Key for Chaim
  Owner:
    Type: String
    Description: The owner of the product
  Product:
    Type: String
    Description: The product this stack provides
  Environment:
    Type: String
    Description: The environment the product will be built in
Resources:
  ChaimCognito:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.eu-west-1.amazonaws.com/chaimcloudformationtemplates/b79d9bce2e781cccbd35cec5810fce31.template
      Parameters:
        Owner:
          Ref: Owner
        Product:
          Ref: Product
        Environment:
          Ref: Environment
  ChaimIAM:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.eu-west-1.amazonaws.com/chaimcloudformationtemplates/790544640a047a598d92a60176f579b1.template
      Parameters:
        CognitoUserPoolId:
          Fn::GetAtt:
          - ChaimCognito
          - Outputs.CognitoUserPoolId
        ChaimUser:
          Ref: ChaimUser
        ChaimUserRole:
          Ref: ChaimUserRole
        ChaimRole:
          Ref: ChaimRole
        ChaimKMSKey:
          Ref: ChaimKMSKey
    DependsOn: ChaimCognito
  ChaimKMS:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.eu-west-1.amazonaws.com/chaimcloudformationtemplates/4e0ca6b645a5fe6bfd77ffe7bc9be8a0.template
      Parameters:
        ChaimRole:
          Ref: ChaimRole
        Owner:
          Ref: Owner
        Product:
          Ref: Product
        Environment:
          Ref: Environment
    DependsOn: ChaimIAM
