---
  AWSTemplateFormatVersion: 2010-09-09
  Parameters: 
    CognitoUserPoolId:
      Type: String
      Description: The Cognito User Pool Id
    ChaimUser:
      Type: String
      Description: The IAM Chaim User
    ChaimRole:
      Type: String
      Description: Tag for Chaim User
    ChaimKMSKey:
      Type: String
      Description: The KMS Key for Chaim
    Owner:
      Type: String
      Description: The owner of the product
    Product:
      Type: String
      Description: The product this stack provides
    Environment:
      Type: String
      Description: The environment the product will be built in
  Resources:
    ChaimMasterUser:
      Type: AWS::IAM::User
      Properties:
        UserName: !Ref ChaimUser
        ManagedPolicyArns:
          - !Ref STSAssumeRole
          - !Ref ChaimManageAccessKey
        Tags:
          - Key: Role
            Value: !Ref ChaimRole
          - Key: Name
            Value: !Ref ChaimUser
      DependsOn: 
        - STSAssumeRole
        - ChaimManageAccessKey
    ChaimCognitoManageUser:
      Type: AWS::IAM::ManagedPolicy
      Properties:
        ManagedPolicyName: ChaimCognitoManageUser
        PolicyDocument:
          Version: 2012-10-17
          Statement:
            Sid: ChaimCognitoManageUser0
            Effect: Allow
            Action:
              - cognito-idp:AdminDeleteUser
              - cognito-idp:AdminEnableUser
              - cognito-idp:AdminCreateUser
              - cognito-idp:AdminDisableUser
              - cognito-idp:AdminGetUser
              - cognito-idp:ListUser
            Resource:
              !Sub
                - "arn:aws:cognito-idp:${AWS::Region}:${AWS::AccountId}:userpool/${CognitoUser}"
                - { CognitoUser: !Ref CognitoUserPoolId }
    ChaimManageAccessKey:
      Type: AWS::IAM::ManagedPolicy
      Properties:
        ManagedPolicyName: ChaimManageAccessKey
        PolicyDocument:
          Version: 2012-10-17
          Statement:
            Sid: ChaimManageAccessKey0
            Effect: Allow
            Action:
              - iam:DeleteAccessKey
              - iam:GetAccessKeyLastUsed
              - iam:UpdateAccessKey
              - iam:GetUser
              - iam:CreateAccessKey
              - iam:ListAccessKeys
            Resource:
              !Sub
                - "arn:aws:iam::${AWS::AccountId}:user/${User}"
                - { User: !Ref ChaimUser }
    ChaimParameterstoreWrite:
      Type: AWS::IAM::ManagedPolicy
      Properties:
        ManagedPolicyName: ChaimParameterstoreWrite
        PolicyDocument:
          Version: 2012-10-17
          Statement:
            Sid: ChaimParameterstoreWrite0
            Effect: Allow
            Action:
              - ssm:PutParameter
              - kms:Decrypt
              - kms:Encrypt
              - ssm:GetParametersByPath
              - ssm:GetParameters
              - ssm:GetParameter
            Resource:
              - !Sub
                - "arn:aws:kms:${AWS::Region}:${AWS::AccountId}:key/${Key}"
                - { Key: !Ref KeyId }
              - !Sub
                - "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/sre/chaim/*"
            Sid: ChaimParameterstoreWrite1
            Effect: Allow
            Action: ssm:DescribeParameters
            Resource: "*"
    ChaimPublishToSNS:
      Type: AWS::IAM::ManagedPolicy
      Properties:
        ManagedPolicyName: ChaimPublishToSNS
        PolicyDocument:
          Version: 2012-10-17
          Statement:
            Sid: ChaimPublishToSNS0
            Effect: Allow
            Action: sns:Publish
            Resource:
              - !Sub "arn:aws:sns:${AWS::Region}:${AWS::AccountId}:chaim-slack-helper"
              - !Sub "arn:aws:sns:${AWS::Region}:${AWS::AccountId}:ChaimSlackBeta"
              - !Sub "arn:aws:sns:${AWS::Region}:${AWS::AccountId}:ChaimSlackProd"
              - !Sub "arn:aws:sns:${AWS::Region}:${AWS::AccountId}:sre-honeypass"
              - !Sub "arn:aws:sns:${AWS::Region}:${AWS::AccountId}:sre-honeyhub"
              - !Sub "arn:aws:sns:${AWS::Region}:${AWS::AccountId}:sre-hc-pw-reset"
    CognitoGetUserStatus:
      Type: AWS::IAM::ManagedPolicy
      Properties:
        ManagedPolicyName: CognitoGetUserStatus
        PolicyDocument:
          Version: 2012-10-17
          Statement:
            Sid: CognitoGetUserStatus0
            Effect: Allow
            Action:
              - cognito-idp:AdminGetUser
              - cognito-idp:List*
            Resource:
              !Sub
                - "arn:aws:cognito-idp:${AWS::Region}:${AWS::AccountId}:userpool/${CognitoUser}"
                - { CognitoUser: !Ref CognitoUserPoolId }
    CognitoManageUserPool:
      Type: AWS::IAM::ManagedPolicy
      Properties:
        ManagedPolicyName: CognitoManageUserPool
        PolicyDocument:
          Version: 2012-10-17
          Statement:
            Sid: CognitoManageUserPool0
            Effect: Allow
            Action:
              - cognito-idp:ListUsersInGroup
              - cognito-idp:ListGroups
              - cognito-idp:AdminListDevices
              - cognito-idp:AdminCreateUser
              - cognito-idp:ListDevices
              - cognito-idp:AdminDisableUser
              - cognito-idp:AdminListGroupsForUser
              - cognito-idp:AdminGetUser
              - cognito-idp:ListUserPoolClients
              - cognito-idp:ListUserImportJobs
            Resource:
              !Sub
                - "arn:aws:cognito-idp:${AWS::Region}:${AWS::AccountId}:userpool/${CognitoUser}"
                - { CognitoUser: !Ref CognitoUserPoolId }
    ParamStoreRead:
      Type: AWS::IAM::ManagedPolicy
      Properties:
        ManagedPolicyName: ParamStoreRead
        PolicyDocument:
          Version: 2012-10-17
          Statement:
            Sid: ParamStoreRead0
            Effect: Allow
            Action: kms:Decrypt
            Resource: 
              !Sub
                - "arn:aws:kms:${AWS::Region}:${AWS::AccountId}:key/${Key}"
                - { Key:  !Ref ChaimKMSKey }
            Sid: ParamStoreRead1
            Effect: Allow
            Action:
              - ssm:DescribeParameters",
              - ssm:GetParametersByPath",
              - ssm:GetParameters",
              - ssm:GetParameter"
            Resource: "*"
    STSAssumeRole:
      Type: AWS::IAM::ManagedPolicy
      Properties:
        ManagedPolicyName: STSAssumeRole
        PolicyDocument:
          Version: 2012-10-17
          Statement:
              Sid: STSAssumeRole0
              Effect: Allow
              Action:
                - sts:GetSessionToken
                - sts:AssumeRole
              Resource: "*"
