---
  AWSTemplateFormatVersion: 2010-09-09
  Parameters:
    ChaimCIDROctet0:
      Type: String
      Description: First octet of CIDR Block
    ChaimCIDROctet1:
      Type: String
      Description: Second octet of CIDR Block
    Owner:
      Type: String
      Description: The owner of the product
    Product:
      Type: String
      Description: The product this stack provides
    Environment:
      Type: String
      Description: The environment the product will be built in
  Resources:
    ChaimVPC:
      Type: AWS::EC2::VPC
      Properties: 
        CidrBlock: 
          !Sub
            - "${CIDR0}.${CIDR1}.0.0/16"
            - CIDR0: !Ref ChaimCIDROctet0
              CIDR1: !Ref ChaimCIDROctet1
        Tags:
          - Key: Name
            Value: ChaimDbNetwork
          - Key: Owner
            Value: !Ref Owner
          - Key: Product
            Value: !Ref Product
          - Key: Environment
            Value: !Ref Environment
          - Key: Role
            Value: ChaimVPC
    ChaimSubnet0:
      Type: AWS::EC2::Subnet
      Properties:
        VpcId: !Ref ChaimVPC
        AvailabilityZone:
          !Sub "${AWS::Region}a"
        CidrBlock:
          !Sub
            - "${CIDR0}.${CIDR1}.0.0/24"
            - CIDR0: !Ref ChaimCIDROctet0
              CIDR1: !Ref ChaimCIDROctet1
        MapPublicIpOnLaunch: True
        Tags:
          - Key: Name
            Value: ChaimSubnet0
          - Key: Owner
            Value: !Ref Owner
          - Key: Product
            Value: !Ref Product
          - Key: Environment
            Value: !Ref Environment
          - Key: Role
            Value: ChaimSubnet
      DependsOn: ChaimVPC
    ChaimSubnet1:
      Type: AWS::EC2::Subnet
      Properties:
        VpcId: !Ref ChaimVPC
        AvailabilityZone:
          !Sub "${AWS::Region}b"
        CidrBlock:
          !Sub
            - "${CIDR0}.${CIDR1}.1.0/24"
            - CIDR0: !Ref ChaimCIDROctet0
              CIDR1: !Ref ChaimCIDROctet1
        Tags:
          - Key: Name
            Value: ChaimSubnet1
          - Key: Owner
            Value: !Ref Owner
          - Key: Product
            Value: !Ref Product
          - Key: Environment
            Value: !Ref Environment
          - Key: Role
            Value: ChaimSubnet
      DependsOn: ChaimVPC
    ChaimSubnet2:
      Type: AWS::EC2::Subnet
      Properties:
        VpcId: !Ref ChaimVPC
        AvailabilityZone:
          !Sub "${AWS::Region}c"
        CidrBlock:
          !Sub
            - "${CIDR0}.${CIDR1}.2.0/24"
            - CIDR0: !Ref ChaimCIDROctet0
              CIDR1: !Ref ChaimCIDROctet1
        Tags:
          - Key: Name
            Value: ChaimSubnet2
          - Key: Owner
            Value: !Ref Owner
          - Key: Product
            Value: !Ref Product
          - Key: Environment
            Value: !Ref Environment
          - Key: Role
            Value: ChaimSubnet
      DependsOn: ChaimVPC
    ChaimEIP:
      Type: AWS::EC2::EIP
      Properties:
        Domain: VPC
        Tags:
          - Key: Name
            Value: ChaimEIP
          - Key: Owner
            Value: !Ref Owner
          - Key: Product
            Value: !Ref Product
          - Key: Environment
            Value: !Ref Environment
          - Key: Role
            Value: ChaimEIP
      DependsOn: ChaimVPC
    ChaimNatGateway:
      Type: AWS::EC2::NatGateway
      Properties:
        AllocationId: !GetAtt ChaimEIP.AllocationId
        SubnetId: !Ref ChaimSubnet0
        Tags:
          - Key: Name
            Value: ChaimNatGateway
          - Key: Owner
            Value: !Ref Owner
          - Key: Product
            Value: !Ref Product
          - Key: Environment
            Value: !Ref Environment
          - Key: Role
            Value: ChaimNatGateway
      DependsOn: ChaimEIP
    ChaimInternetGateway:
      Type: AWS::EC2::InternetGateway
      Properties:
        Tags:
          - Key: Name
            Value: ChaimInternetGateway
          - Key: Owner
            Value: !Ref Owner
          - Key: Product
            Value: !Ref Product
          - Key: Environment
            Value: !Ref Environment
          - Key: Role
            Value: ChaimInternetGateway
      DependsOn: ChaimVPC
    ChaimVPCGatewayAttachment:
      Type: AWS::EC2::VPCGatewayAttachment
      Properties:
        VpcId: !Ref ChaimVPC
        InternetGatewayId: !Ref ChaimInternetGateway
      DependsOn: ChaimInternetGateway
    ChaimRouteTablePublic:
      Type: AWS::EC2::RouteTable
      Properties:
        VpcId: !Ref ChaimVPC
        Tags:
          - Key: Name
            Value: ChaimRouteTablePublic
          - Key: Owner
            Value: !Ref Owner
          - Key: Product
            Value: !Ref Product
          - Key: Environment
            Value: !Ref Environment
          - Key: Role
            Value: ChaimRouteTablePublic
      DependsOn: ChaimVPC
    ChaimRouteTablePrivate:
      Type: AWS::EC2::RouteTable
      Properties:
        VpcId: !Ref ChaimVPC
        Tags:
          - Key: Name
            Value: ChaimRouteTablePrivate
          - Key: Owner
            Value: !Ref Owner
          - Key: Product
            Value: !Ref Product
          - Key: Environment
            Value: !Ref Environment
          - Key: Role
            Value: ChaimRouteTablePrivate
      DependsOn: ChaimVPC
    ChaimRoutePublic:
      Type: AWS::EC2::Route
      Properties:
        DestinationCidrBlock: 0.0.0.0/0
        GatewayId: !Ref ChaimInternetGateway
        RouteTableId: !Ref ChaimRouteTablePublic
      DependsOn: ChaimRouteTablePublic
    ChaimRoutePrivate:
      Type: AWS::EC2::Route
      Properties:
        DestinationCidrBlock: 0.0.0.0/0
        NatGatewayId: !Ref ChaimNatGateway
        RouteTableId: !Ref ChaimRouteTablePrivate
      DependsOn: ChaimRouteTablePrivate
    ChaimSubnetRouteTableAssociation0:
      Type: AWS::EC2::SubnetRouteTableAssociation
      Properties:
        RouteTableId: !Ref ChaimRouteTablePublic
        SubnetId: !Ref ChaimSubnet0
      DependsOn: 
        - ChaimSubnet0
        - ChaimRouteTablePublic
    ChaimSubnetRouteTableAssociation1:
      Type: AWS::EC2::SubnetRouteTableAssociation
      Properties:
        RouteTableId: !Ref ChaimRouteTablePrivate
        SubnetId: !Ref ChaimSubnet1
      DependsOn: 
        - ChaimSubnet1
        - ChaimRouteTablePrivate
    ChaimSubnetRouteTableAssociation2:
      Type: AWS::EC2::SubnetRouteTableAssociation
      Properties:
        RouteTableId: !Ref ChaimRouteTablePrivate
        SubnetId: !Ref ChaimSubnet2
      DependsOn: 
        - ChaimSubnet2
        - ChaimRouteTablePrivate
    ChaimDbAccessSG:
      Type: AWS::EC2::SecurityGroup
      Properties:
        GroupDescription: 'Security group for access to the chaim database'
        GroupName: ChaimDbAccessSG
        VpcId: !Ref ChaimVPC
        Tags:
          - Key: Name
            Value: ChaimDbAccessSG
          - Key: Owner
            Value: !Ref Owner
          - Key: Product
            Value: !Ref Product
          - Key: Environment
            Value: !Ref Environment
          - Key: Role
            Value: ChaimDbAccessSG
  Outputs:
    ChaimVPCId:
      Value: !Ref ChaimVPC
    ChaimSubnetaId:
      Value: !Ref ChaimSubnet0
    ChaimSubnetbId:
      Value: !Ref ChaimSubnet1
    ChaimSubnetcId:
      Value: !Ref ChaimSubnet2
    ChaimEIPId:
      Value: !GetAtt ChaimEIP.AllocationId
    ChaimNatGatewayId:
      Value: !Ref ChaimNatGateway
    ChaimInternetGatewayId:
      Value: !Ref ChaimInternetGateway
    ChaimVPCGatewayAttachmentId:
      Value: !Ref ChaimVPCGatewayAttachment
    ChaimRouteTablePublicId:
      Value: !Ref ChaimRouteTablePublic
    ChaimRouteTablePrivateId:
      Value: !Ref ChaimRouteTablePrivate
    ChaimRoutePublicId:
      Value: !Ref ChaimRoutePublic
    ChaimRoutePrivateId:
      Value: !Ref ChaimRoutePrivate
    ChaimDbAccessSGId:
      Value: !GetAtt ChaimDbAccessSG.GroupId
