---
  AWSTemplateFormatVersion: 2010-09-09
  Parameters: 
    ChaimUser:
      Type: String
      Description: The IAM Chaim User
    ChaimUserRole:
      Type: String
      Description: Tag for Chaim User
    ChaimLambdaRDSRoleName:
      Type: String
      Description: Tag for Chaim Lambda RDS Role
    ChaimLambdaKeymanRoleName:
      Type: String
      Description: Tag for Chaim Lambda Keyman Role
    Owner:
      Type: String
      Description: The owner of the product
    Product:
      Type: String
      Description: The product this stack provides
    Environment:
      Type: String
      Description: The environment the product will be built in
  Resources:
    ChaimCognito:
      Type: AWS::CloudFormation::Stack
      Properties:
        TemplateURL: chaim_cognito.yaml
        Parameters:
          Owner: !Ref Owner
          Product: !Ref Product
          Environment: !Ref Environment        
    ChaimIAM:
      Type: AWS::CloudFormation::Stack
      Properties:
        TemplateURL: chaim_iam.yaml
        Parameters:
          ChaimCognitoUserPool: !GetAtt ChaimCognito.Outputs.ChaimCognitoUserPoolId
          ChaimLambdaRDSRoleName: !Ref ChaimLambdaRDSRoleName
          ChaimLambdaKeymanRoleName: !Ref ChaimLambdaKeymanRoleName
          ChaimUser: !Ref ChaimUser
          ChaimUserRole: !Ref ChaimUserRole
          Environment: !Ref Environment
          Owner: !Ref Owner
          Product: !Ref Product
      DependsOn: ChaimCognito
    ChaimKMS:
      Type: AWS::CloudFormation::Stack
      Properties:
        TemplateURL: chaim_kms.yaml
        Parameters:
          ChaimLambdaRDSRoleName: !Ref ChaimLambdaRDSRoleName
          Environment: !Ref Environment
          Owner: !Ref Owner
          Product: !Ref Product
      DependsOn: ChaimIAM
    ChaimIAM2:
      Type: AWS::CloudFormation::Stack
      Properties:
        TemplateURL: chaim_iam_2.yaml
        Parameters:
          ChaimKMSKey: !GetAtt ChaimKMS.Outputs.ChaimKMSKeyId
          ChaimLambdaRDSRole: !GetAtt ChaimIAM.Outputs.ChaimLambdaRDSRoleId
          ChaimLambdaKeymanRole: !GetAtt ChaimIAM.Outputs.ChaimLambdaKeymanRoleId
          Environment: !Ref Environment
          Owner: !Ref Owner
          Product: !Ref Product
      DependsOn: ChaimKMS
